### ISSUE TITLE
Creacion de CRUD 

### ISSUE THREAD

**Issue by thetygerpotatto** [thetygerpotatto/MiniProyecto1JDG#1]
Realizar una aplicación que por consola pueda:
1. Insertar dinero ahorrado
2. Actualizar dinero ahorrado
3. Eliminar dinero ahorrado
4. Buscar cliente por nombre y ver su ahorro
5. Listar todos los clientes

**Comment by Gabriel-Uraza611** [comment]
se termino de crear la primera parte del proyecto con exito, el CRUD esta hecho!
